steps:
  # Build API image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'infra/docker/api.Dockerfile', '-t', 'gcr.io/$PROJECT_ID/api:$_COMMIT_SHA', '.']
    id: 'build-api'

  # Build Web image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'infra/docker/web.Dockerfile'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_BASE=https://api-$PROJECT_NUMBER.asia-northeast1.run.app'
      - '-t'
      - 'gcr.io/$PROJECT_ID/web:$_COMMIT_SHA'
      - '.'
    id: 'build-web'


  # Build Host image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'infra/docker/host.Dockerfile', '-t', 'gcr.io/$PROJECT_ID/host:$_COMMIT_SHA', '.']
    id: 'build-host'

  # LiveKit Cloud is used instead of self-hosted LiveKit

  # Push images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/api:$_COMMIT_SHA']
    waitFor: ['build-api']
    id: 'push-api'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/web:$_COMMIT_SHA']
    waitFor: ['build-web']
    id: 'push-web'


  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/host:$_COMMIT_SHA']
    waitFor: ['build-host']
    id: 'push-host'

  # LiveKit Cloud push not needed

  # Update Cloud Run services with new images
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Update API service with secret references
        gcloud run services update api --region=asia-northeast1 --image=gcr.io/$PROJECT_ID/api:$_COMMIT_SHA \
          --set-secrets="POSTGRES_PASSWORD=postgres-password:latest,OPENAI_API_KEY=openai-api-key:latest,LIVEKIT_API_KEY=livekit-api-key:latest,LIVEKIT_API_SECRET=livekit-api-secret:latest,LIVEKIT_URL=livekit-url:latest,POSTGRES_HOST=postgres-host:latest,POSTGRES_PORT=postgres-port:latest,POSTGRES_USER=postgres-user:latest,POSTGRES_DB=postgres-db:latest" \
          --set-env-vars="ALLOWED_ORIGIN=https://web-$PROJECT_NUMBER.asia-northeast1.run.app"
        
        # Update Web service
        gcloud run services update web --region=asia-northeast1 --image=gcr.io/$PROJECT_ID/web:$_COMMIT_SHA \
          --set-env-vars="NEXT_PUBLIC_API_BASE=https://api-$PROJECT_NUMBER.asia-northeast1.run.app"
        
        
        # Update Host service with secret references
        gcloud run services update host --region=asia-northeast1 --image=gcr.io/$PROJECT_ID/host:$_COMMIT_SHA \
          --set-secrets="LIVEKIT_API_KEY=livekit-api-key:latest,LIVEKIT_API_SECRET=livekit-api-secret:latest,OPENAI_API_KEY=openai-api-key:latest,LIVEKIT_WS_URL=livekit-url:latest"
        
        # LiveKit Cloud update not needed
    waitFor: ['push-api', 'push-web', 'push-host']
    id: 'update-services'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/api:$_COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/web:$_COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/host:$_COMMIT_SHA'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Substitution variables
substitutions:
  _COMMIT_SHA: 'latest'

# Timeout
timeout: '1200s'
