version: "3.8"

services:
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881"
    environment:
      LIVEKIT_CONFIG: |
        port: 7880
        rtc:
          udp_port: 7881
          use_external_ip: false
        redis:
          address: localhost:6379
        keys:
          APIKey: devkey
          APISecret: secret
        webhook:
          api_key: webhookkey
        development: true
    command: --config /etc/livekit.yaml
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
