port: 7880
rtc:
  udp_port: 7881
  use_external_ip: false
redis:
  address: redis:6379
keys:
  APIKey: devkey
  APISecret: secret
webhook:
  api_key: webhookkey
development: true
room:
  auto_create: true