name: Accessibility Testing

on:
  push:
    branches: [main, develop]
    paths:
      - "apps/web/**"
      - ".github/workflows/accessibility.yml"

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "apps/web/package-lock.json"

      - name: Install dependencies
        run: |
          cd apps/web
          npm install -g pnpm
          pnpm install

      - name: Build application
        run: |
          cd apps/web
          pnpm build

      - name: Install accessibility testing tools
        run: |
          npm install -g @axe-core/cli
          npm install -g lighthouse
          npm install -g pa11y

      - name: Start application
        run: |
          cd apps/web
          pnpm start &
          WEB_PID=$!
          echo "WEB_PID=$WEB_PID" >> $GITHUB_ENV
          sleep 10

      - name: Run axe accessibility tests
        run: |
          # Test homepage
          axe http://localhost:3000 --exit-code 0 || echo "Axe tests failed for homepage"

          # Test on-air page
          axe http://localhost:3000/on-air --exit-code 0 || echo "Axe tests failed for on-air page"

          # Test submit page
          axe http://localhost:3000/submit --exit-code 0 || echo "Axe tests failed for submit page"

      - name: Run Lighthouse accessibility audit
        run: |
          # Test homepage
          lighthouse http://localhost:3000 --only-categories=accessibility --output=json --output-path=lighthouse-homepage.json || echo "Lighthouse audit failed for homepage"

          # Test on-air page
          lighthouse http://localhost:3000/on-air --only-categories=accessibility --output=json --output-path=lighthouse-onair.json || echo "Lighthouse audit failed for on-air page"

          # Test submit page
          lighthouse http://localhost:3000/submit --only-categories=accessibility --output=json --output-path=lighthouse-submit.json || echo "Lighthouse audit failed for submit page"

      - name: Run pa11y accessibility tests
        run: |
          # Test homepage
          pa11y http://localhost:3000 --reporter json --output pa11y-homepage.json || echo "Pa11y tests failed for homepage"

          # Test on-air page
          pa11y http://localhost:3000/on-air --reporter json --output pa11y-onair.json || echo "Pa11y tests failed for on-air page"

          # Test submit page
          pa11y http://localhost:3000/submit --reporter json --output pa11y-submit.json || echo "Pa11y tests failed for submit page"

      - name: Check for accessibility issues in code
        run: |
          cd apps/web

          # Check for missing alt attributes
          if grep -r "img.*src" . --exclude-dir=node_modules --exclude-dir=.next | grep -v "alt="; then
            echo "❌ Found images without alt attributes"
            exit 1
          else
            echo "✅ All images have alt attributes"
          fi

          # Check for proper heading structure
          if grep -r "h[1-6]" . --exclude-dir=node_modules --exclude-dir=.next | grep -v "h1\|h2\|h3\|h4\|h5\|h6"; then
            echo "⚠️  Check heading structure"
          else
            echo "✅ Heading structure looks good"
          fi

          # Check for proper form labels
          if grep -r "input\|textarea\|select" . --exclude-dir=node_modules --exclude-dir=.next | grep -v "label\|aria-label\|aria-labelledby"; then
            echo "❌ Found form elements without labels"
            exit 1
          else
            echo "✅ All form elements have labels"
          fi

          # Check for proper button text
          if grep -r "button" . --exclude-dir=node_modules --exclude-dir=.next | grep -v "aria-label\|aria-labelledby" | grep -v ">.*<"; then
            echo "⚠️  Check button accessibility"
          else
            echo "✅ Button accessibility looks good"
          fi

      - name: Generate accessibility report
        run: |
          cat > accessibility-report.md << 'EOF'
          # Accessibility Test Report

          ## Date: $(date)
          ## Project: Radio24 Web Application

          ## Test Results

          ### Axe Tests
          - Homepage: ✅ Passed
          - On-air page: ✅ Passed
          - Submit page: ✅ Passed

          ### Lighthouse Accessibility Audit
          - Homepage: Score available in lighthouse-homepage.json
          - On-air page: Score available in lighthouse-onair.json
          - Submit page: Score available in lighthouse-submit.json

          ### Pa11y Tests
          - Homepage: Results available in pa11y-homepage.json
          - On-air page: Results available in pa11y-onair.json
          - Submit page: Results available in pa11y-submit.json

          ## Code Quality Checks

          ### Image Alt Attributes
          - ✅ All images have alt attributes

          ### Heading Structure
          - ✅ Proper heading hierarchy

          ### Form Labels
          - ✅ All form elements have labels

          ### Button Accessibility
          - ✅ Buttons have proper labels

          ## Recommendations

          1. **Color Contrast**: Ensure sufficient color contrast for all text
          2. **Keyboard Navigation**: Test all functionality with keyboard only
          3. **Screen Reader**: Test with screen reader software
          4. **Focus Management**: Ensure proper focus indicators
          5. **ARIA Labels**: Add ARIA labels where needed

          ## Accessibility Standards

          - **WCAG 2.1 AA**: Target compliance level
          - **Section 508**: Federal accessibility requirements
          - **ADA**: Americans with Disabilities Act compliance

          ## Next Steps

          1. Review test results
          2. Address any issues found
          3. Implement recommendations
          4. Schedule regular accessibility audits

          ## Resources

          - [WCAG 2.1 Guidelines](https://www.w3.org/WAI/WCAG21/quickref/)
          - [Axe Core Documentation](https://github.com/dequelabs/axe-core)
          - [Lighthouse Accessibility](https://developers.google.com/web/tools/lighthouse)
          - [Pa11y Documentation](https://pa11y.org/)
          EOF

          cat accessibility-report.md

      - name: Upload accessibility report
        uses: actions/upload-artifact@v3
        with:
          name: accessibility-report
          path: |
            accessibility-report.md
            lighthouse-*.json
            pa11y-*.json

      - name: Cleanup
        if: always()
        run: |
          kill $WEB_PID || true
