name: Database Backup

on:
  schedule:
    - cron: "0 3 * * *" # Every day at 3 AM
  workflow_dispatch:

env:
  PROJECT_ID: radio24-project
  REGION: asia-northeast1

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Create database backup
        run: |
          BACKUP_ID="radio24-backup-$(date +%Y%m%d-%H%M%S)"

          gcloud sql backups create $BACKUP_ID \
            --instance=radio24-db \
            --description="Automated backup created on $(date)"

          echo "Backup created: $BACKUP_ID"

      - name: Clean up old backups
        run: |
          # Keep only the last 30 days of backups
          CUTOFF_DATE=$(date -d '30 days ago' +%Y-%m-%d)

          OLD_BACKUPS=$(gcloud sql backups list \
            --instance=radio24-db \
            --filter="creationTime<$CUTOFF_DATE" \
            --format="value(id)")

          for backup in $OLD_BACKUPS; do
            echo "Deleting old backup: $backup"
            gcloud sql backups delete $backup \
              --instance=radio24-db \
              --quiet || echo "Failed to delete $backup"
          done

      - name: Export data to Cloud Storage
        run: |
          BUCKET_NAME="radio24-backups"
          EXPORT_FILE="radio24-export-$(date +%Y%m%d-%H%M%S).sql"

          # Create bucket if it doesn't exist
          gsutil mb gs://$BUCKET_NAME || echo "Bucket may already exist"

          # Export database to Cloud Storage
          gcloud sql export sql radio24-db \
            gs://$BUCKET_NAME/$EXPORT_FILE \
            --database=radio24 \
            --offload

          echo "Database exported to: gs://$BUCKET_NAME/$EXPORT_FILE"

      - name: Clean up old exports
        run: |
          BUCKET_NAME="radio24-backups"

          # Delete exports older than 90 days
          gsutil -m rm -r gs://$BUCKET_NAME/radio24-export-$(date -d '90 days ago' +%Y%m%d)* || echo "No old exports to clean up"
