name: LiveKit Deployment

on:
  push:
    branches: [main]
    paths:
      - "infra/livekit/**"
      - ".github/workflows/livekit.yml"

env:
  PROJECT_ID: radio24-project
  REGION: asia-northeast1

jobs:
  deploy-livekit:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Enable required APIs
        run: |
          gcloud services enable cloudbuild.googleapis.com
          gcloud services enable run.googleapis.com
          gcloud services enable container.googleapis.com

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build LiveKit image
        run: |
          docker build -f infra/livekit/Dockerfile -t gcr.io/${{ env.PROJECT_ID }}/livekit:${{ github.sha }} infra/livekit/
          docker push gcr.io/${{ env.PROJECT_ID }}/livekit:${{ github.sha }}

      - name: Deploy LiveKit to Cloud Run
        run: |
          gcloud run deploy livekit \
            --image gcr.io/${{ env.PROJECT_ID }}/livekit:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port 7880 \
            --memory 2Gi \
            --cpu 2 \
            --max-instances 3 \
            --set-env-vars "LIVEKIT_KEYS=${{ secrets.LIVEKIT_API_KEY }}: ${{ secrets.LIVEKIT_API_SECRET }}"

      - name: Get LiveKit URL
        run: |
          LIVEKIT_URL=$(gcloud run services describe livekit --region=${{ env.REGION }} --format="value(status.url)")
          echo "LIVEKIT_URL=$LIVEKIT_URL" >> $GITHUB_ENV
          echo "LiveKit deployed at: $LIVEKIT_URL"
